### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by harshitmahapatra** [MassimoWRivolta/PRSA#1]
Hi,

Thank you for making these functions publicly available. 
I want to make a python port of your functions but without a specified license, I am unable to do so.

Would you mind adding a license to the code, so that it is clear as to who can use the code and under what conditions?.
If you want to make the code open source you can add any of the popular open-source licenses such as Apache 2.0, MIT, GPL, etc.

Thank you very much for your time!

**Comment by MassimoWRivolta** [comment]
Hi @harshitmahapatra 
I have added the licence (MIT) to the code. Feel free to use it.

Massimo

**Comment by martinfrasch** [comment]
Great. Thanks, Massimo!!

**Comment by harshitmahapatra** [comment]
Thank you very much :)!
